from vectorization.distance_of_entity_to_quote_vector import get_distance_of_entity_to_quote_vector
from vectorization.entity_position_vector import get_entity_position_vector
from vectorization.frequency_of_entity_vector import get_frequency_of_entity_vector
from vectorization.quote_vector import get_quote_vector
from vectorization.relative_entity_position_vector import get_relative_entity_position_vector
from vectorization.relative_frequency_ranking_vector import get_relative_frequency_ranking_vector
from vectorization.entity_tag_vector import get_is_person_vector, get_is_location_vector, get_is_organization_vector
from vectorization.title_vector import get_title_relative_vector, get_title_similarity_relative_vector
