from .distance_of_entity_to_quote import get_distance_of_entity_to_quote_vector
from .entity_position_vector import get_entity_position_vector
from .frequency_of_entity_vector import get_frequency_of_entity_vector
from .quote_vector import get_quote_vector
from .relative_entity_position import get_relative_entity_position_vector
from .relative_frequency_ranking import get_relative_frequency_ranking_vector
