from .distance_of_entity_to_quote_vector import get_distance_of_entity_to_quote_vector, get_distance_of_entity_to_quote_relative_vector
from .entity_position_vector import get_entity_position_vector
from .frequency_of_entity_vector import get_frequency_of_entity_vector
from .quote_vector import get_quote_vector, get_quote_relative_vector
from .relative_entity_position_vector import get_relative_entity_position_vector
from .relative_frequency_ranking_vector import get_relative_frequency_ranking_vector
from .entity_tag_vector import get_is_person_vector, get_is_location_vector, get_is_organization_vector
from .title_vector import get_title_relative_vector, get_title_similarity_relative_vector, get_title_vector, get_title_similarity_vector, get_quote_topic_vector
from .speech_verb_vector import get_speech_verb_vector, get_speech_verb_relative_vector
from .entity_is_in_quote import get_entity_is_in_quote
